[project]
name = "1-research-analyst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.203.1",
    "crewai-tools>=0.76.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.50.0",
]
